name: Deploy to GitHub Pages

on:
  push:
    branches: [ "main" ] # Sesuai dengan branch 'main' di repo lu

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Use Node.js 20.x
      uses: actions/setup-node@v4
      with:
        node-version: 20.x
        cache: 'npm'

    - name: Install Dependencies
      run: npm install

    - name: Build with Vite
      # Ditambahkan flag base agar aset aplikasi lu mengarah ke /LN-Translator/ dan tidak blank putih
      run: npx vite build --base=/LN-Translator/

    - name: Upload Artifact
      uses: actions/upload-pages-artifact@v3
      with:
        path: ./dist # Langsung ambil folder dist dari root

    - name: Deploy to GitHub Pages
      id: deployment
      uses: actions/deploy-pages@v4
